### ISSUE TITLE
YouTube ads home(beranda)

### ISSUE THREAD

**Issue by Jokopentil** [uBlockOrigin/uBOL-home#100]
`https://m.youtube.com/`
![IMG_20231223_194300.jpg](https://github.com/uBlockOrigin/uBOL-home/assets/114223791/8ffe82d6-a3a3-4359-8a01-4cdc1f0d1f0a)

**Comment by Meyers07** [comment]
Normal kalau di mobile, ketika memainkan video tidak ada iklan. Saya tidak menggunakan UBOL di Mobile tetapi menggunakan Brave dengan setting Maksimum Shield
