### ISSUE TITLE
uBlock Origin Lite Edge Addon Looks Outdated

### ISSUE THREAD

**Issue by golf1487** [uBlockOrigin/uBOL-home#101]
uBlock Origin Lite version on Edge Add-ons - Version 2023.12.4.1333 / Updated December 5, 2023
uBlock Origin Lite version on Chrome Web Store - Version 2023.12.16.1327 / Updated December 19, 2023

Please keep Edge Addon up to date.

**Comment by gorhill** [comment]
2023.12.16.1327 was submitted days ago:

> Microsoft is reviewing your submission currently. Expect to hear back from us in 7 business days.

Please do not open issue about this, just start a discussion next time rather than assuming I am not "keep[ing] Edge Addon up to date".
