### ISSUE TITLE
Enabling uBlock Origin on Google Chrome directly disables the Performance 

### ISSUE THREAD

**Issue by xiaolin1991** [uBlockOrigin/uBOL-home#103]
Enabling uBlock Origin on Google Chrome directly disables the Performance - Speed feature inside the browser settings. Please help resolve this issue. Thank you.

![1](https://github.com/uBlockOrigin/uBOL-home/assets/113982716/a37a6e80-9e27-46a1-b5cd-2e4c4e01ef76)

![2](https://github.com/uBlockOrigin/uBOL-home/assets/113982716/2f9f295b-2194-4b80-bcb8-9085ab91a94e)

**Comment by gorhill** [comment]
Here is for uBlock Origin Lite (uBOL), you are using uBlock Origin (not Lite, uBO).

What your screenshot shows is related to prefetching, which is disabled by default in uBO. You can change the setting as you wish: <https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-prefetching>.

**Comment by stephenhawk8054** [comment]
@gorhill I just realized, looks like we can't disable prefetching in uBOL?

**Comment by gorhill** [comment]
The API is there: <https://developer.chrome.com/docs/extensions/reference/api/privacy>. But last time I checked, `<link rel="preconnect" ...>` was not prevented by the setting in MV2, but I don't know about MV3.
