### ISSUE TITLE
Cookie Notices are still showing up in pages

### ISSUE THREAD

**Issue by iahung3** [uBlockOrigin/uBOL-home#104]
I checked everything in `Annoyances`, including `Easylist/UBO - Cookie Notices`.

**Comment by gorhill** [comment]
You provide zero details on how to reproduce. I can't read mind, so I will close as _invalid_. If you ever provide all the details for us to reproduce on our side, I will give a look.

**Comment by iahung3** [comment]
> You provide zero details on how to reproduce. I can't read mind, so I will close as _invalid_. If you ever provide all the details for us to reproduce on our side, I will give a look.

Try visiting stackoverflow.

**Comment by gorhill** [comment]
Provide a URL.

**Comment by iahung3** [comment]
> stackoverflow.

https://stackoverflow.com/

**Comment by gorhill** [comment]
Works fine in _Optimal_ mode, so invalid. Read properly the [description of the extension](https://github.com/uBlockOrigin/uBOL-home#ubo-lite), and next time put more effort in your report, otherwise I will close them as invalid without further comment.

**Comment by iahung3** [comment]
> Works fine in _Optimal_ mode, so invalid. Read properly the [description of the extension](https://github.com/uBlockOrigin/uBOL-home#ubo-lite), and next time put more effort in your report, otherwise I will close them as invalid without further comment.

What about making a template for new issue? I really don't know what to write. My mind is simple. My thinking is also simple. I think it's too obvious. You just have to open a random page with cookie notice to check it. There are so many sites like that, newspapers, forums,... Why do you need me to specify a specific site? I described it as failed for all sites, not a specific site. I really don't expect to be greeted like that.

**Comment by gorhill** [comment]
> What about making a template for new issue?

Yes I will, it's all about free time.
