### ISSUE TITLE
Could you add workaround for Kiwi Browser on Android?

### ISSUE THREAD

**Issue by iahung3** [uBlockOrigin/uBOL-home#105]
The support for extensions on this browser is worse than Firefox Android. But Firefox Android is too heavy, too slow and eating too much memory. The problem with this browser is, unlike Firefox Android, it will not open dialog box to confirm giving permissions for the extension on the specific site (or all sites in the global setting of the extension, too). So, I stuck with the Basic mode that can't effectively block ads. This is really annoying. But I have to stick with Kiwi Browser since it's the only browser on Android support exporting of bookmarks to html. Other browsers will force me to use their sync services which I don't want to. Please have a look at this. Thank you.

**Comment by gorhill** [comment]
> will not open dialog box to confirm giving permissions for the extension on the specific site

The permission dialog is from the browser, so if the browser does not implement it, there is nothing the extension can do.

**Comment by gorhill** [comment]
See <https://github.com/kiwibrowser/src.next/issues/211>, it's a browser issue.

**Comment by gorhill** [comment]
By the way, the desktop chromium browser has its own user interface to manually grant permissions:

![image](https://github.com/uBlockOrigin/uBOL-home/assets/585534/bbb4cde8-a811-4449-85f0-e08063961be5)

uBOL will respect these manually entered permissions, so if there is such user interface in kiwi browser, it might work.

**Comment by iahung3** [comment]
> By the way, the desktop chromium browser has its own user interface to manually grant permissions:
> 
> ![image](https://private-user-images.githubusercontent.com/585534/296302484-bbb4cde8-a811-4449-85f0-e08063961be5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzgyMjAsIm5iZiI6MTcwNTA3NzkyMCwicGF0aCI6Ii81ODU1MzQvMjk2MzAyNDg0LWJiYjRjZGU4LWE4MTEtNDQ0OS04NWYwLWUwODA2Mzk2MWJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQxNjQ1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGY4NzVmZTA0ZmJmMGY1NjVmN2E4MTRjNzA0NjI5N2Y3YjdkY2I4NDlhYmIwMjQ0YmRkMGVkNmQ1NTNiYjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jei8MNVPbnpU6EwC-UKjPkUhCJjzAd_2x_mWIGzvvb0)
> 
> uBOL will respect these manually entered permissions, so if there is such user interface in kiwi browser, it might work.

What if I wanted to grant the permissions to all sites using this way?

**Comment by gorhill** [comment]
The desktop version let you choose "On all sites":

![Screenshot from 2024-01-12 12-08-02](https://github.com/uBlockOrigin/uBOL-home/assets/585534/e1c037f4-4f9d-4eb1-81a2-320c757f8bbd)

In the end, it's responsibility of the browser to let you assign permissions to extensions, there is nothing I can do here.
