### ISSUE TITLE
Feature request: apply filterlists depending on the filtering mode.

### ISSUE THREAD

**Issue by Kees1958** [uBlockOrigin/uBOL-home#107]
Apply filter lists depending on the filtering mode.

The option to adjust the filtering level per website, makes uBOL the best content blocker available. With the three filtering modes I don't have to compromise between risk of website breakage and ad-free web experience. 

I don't know whether below usage scenario's are possible: 

Ideally in basic mode I would only like to apply the default rules plus the region/language filter(s) I have selected (because these always apply).

In optimal mode I would like the basic mode filters plus any of the remaining "miscellaneous" filters. 

In complete mode I would also like to apply the "annoyances" filters I have chosen. Besides blocking and hiding all ads I also want to remove cookies notices and all sorts of overlays and popups call to actions (asking me to become a member, to receive stuff or disable my adblocker). 

Thanks

**Comment by gorhill** [comment]
What you are asking is not possible, there are no way to tell DNR to apply different set of lists of specific sites. This is also not possible in MV2 because this would push the static network filtering engine to be too complex for questionable benefits.
