### ISSUE TITLE
Feature request: add uBO quick fixes and uBO unbreak as dynamic filters

### ISSUE THREAD

**Issue by Kees1958** [uBlockOrigin/uBOL-home#108]
Feature request.

I understand that uBOL stands for LIGHT and has to be kept simple. To circumvent the limitation of updating static filters only when the extension is updates, I would like to suggest to add only 2 (non-changeable) filterlist from UBO assets filters: UBO quick fixes and UBO unbreak and use these two filters as Mv3 dynamic filters (now maximized to 5,000 rules, in future to 15.000).

These filterlists could be maintained in the new Mv3 format, to assure that uBOL does not has to add a a new filtering engine and implement this feature request with minimal code added. 

In this way with every first launch uBOL could get the latest quick fixes and unbreak filters.

**Comment by gorhill** [comment]
Most of the changes to quick-fixes are cosmetic- or content script-based filters, and these cannot be fetched and declaratively injected, so they would have to be left out, and in the end it wouldn't bring much value value to only update a handful (if any) of DNR-based rules while leaving out the far more numerous cosmetic- or content script-based filters.

If all the build scripts prove to be solid over time I may eventually try to publish more often, which would be a better option than flawed and mostly pointless partial update of DNR rules.
