### ISSUE TITLE
 The extension failed to load properly. It might not be able to intercept network requests.

### ISSUE THREAD

**Issue by iahung3** [uBlockOrigin/uBOL-home#109]
The ladder menu show an Error. Click into it open the Extension page with Ublock Origin Lite being reported as such.

**Comment by gorhill** [comment]
I see this regularly when uBO Lite updates, and when looking into it the browser says "internal error" -- it appears the issue is in the browser's own API framework. Restarting the extension always solve the issue.

Seems related: <https://bugs.chromium.org/p/chromium/issues/detail?id=1271154#c127>

**Comment by gorhill** [comment]
What's your exact browser/version?

**Comment by iahung3** [comment]
> What's your exact browser/version?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by iahung3** [comment]
> I see this regularly when uBO Lite updates

Yes, you are right. The error is gone.
