### ISSUE TITLE
uBOLite_2024.1.14.912.chromium.mv3 error?

### ISSUE THREAD

**Issue by Angelique465** [uBlockOrigin/uBOL-home#112]
I don't know if this is normal, but browsing with Ubolite latest version at [https://www.cbssports.com]( https://www.cbssports.com) I often have the error shown in the attached images. 

![ubol02](https://github.com/uBlockOrigin/uBOL-home/assets/147386459/ef3fa21b-34dc-49e8-8aa3-c7e64b89f798)

![ubol00](https://github.com/uBlockOrigin/uBOL-home/assets/147386459/2324a75b-d46a-4130-9387-a8959083b817)

![ubol01](https://github.com/uBlockOrigin/uBOL-home/assets/147386459/5ab2ec8f-b15a-40c5-8789-1e797778bb60)

**Comment by gorhill** [comment]
This is an MV3 quirk, the `onerror` handler does not prevent the exception from reaching the console, while it does prevent with MV2 The exception is normal as a result of using the filter `cbssports.com##+js(aopr, googletag)`.

Not something I can fix, we will have to learn to live with this in MV3.

**Comment by gorhill** [comment]
Workaround is to not check _"Collect errors"_.
