### ISSUE TITLE
Feature: Admin policy option to enable optimal mode by default

### ISSUE THREAD

**Issue by lawndoc** [uBlockOrigin/uBOL-home#113]
Some websites such as [MakeUseOf](https://www.makeuseof.com/) create non-bypassable popups when you have uBOL with Basic mode installed. Increasing the mode to Optimal will actually get rid of the warning and allow you through to the site without disabling ad blocking. For this reason, Optimal mode is a much better user experience when mass deploying to users in an enterprise setting.

Unless I'm missing something, it doesn't appear to be possible for admins to set the default filtering mode in uBOL when deploying. I'd like to request this feature to be added to the extension.

**Comment by gorhill** [comment]
_Optimal_ or _Complete_ require a user gesture so that the browser asks the user whether they want to grant permission, because of this I didn't add the ability to have these as default mode. But if you have documentation that these permissions can be preset by admins such that the extension requesting those permissions won't result in a alert box by the browser, I can add them as choices.

**Comment by lawndoc** [comment]
Ah I forgot about that part. I'll do some research to see if this is possible.

**Comment by lawndoc** [comment]
I did a procmon trace while changing the Site Access setting, and it looks like Edge is writing to `HKCU\Software\Microsoft\Edge\PreferenceMACs\Default\extensions.settings\ddkjiahejlhfcafbddmgiahcphecmpfh`, but the REG_SZ value is just a hash. So it appears that the setting is probably getting stored in a LevelDB somewhere.

It's probably not feasible if we have to patch a particular ldb entry on every host we want to push this to. At least it feels a little sinful at this point.

There was a bunch of other stuff happening with edge in the PML file, but I'm not familiar enough with Chromium to know if something else should have stood out. I'd be happy to share the PML with you via email if you wanted to take a look yourself in case I missed something.

**Comment by lawndoc** [comment]
It looks like it's not going to be possible to remove the permission grant prompt without an update to the manifest. Thanks for entertaining the idea, but it appears to be incompatible with the goal of not granting those permissions by default.

**Comment by gorhill** [comment]
Related webextensions issue: https://github.com/w3c/webextensions/issues/260

**Comment by gorhill** [comment]
I opened an issue in Chrome isse tracker: https://issues.chromium.org/issues/374073122

**Comment by lawndoc** [comment]
I figured out how to auto-consent the permissions for users.

First, add ddkjiahejlhfcafbddmgiahcphecmpfh as an entry value to your SOFTWARE\Policies\Google\Chrome\ExtensionInstallForcelist\

Then, create a REG_SZ value at HKLM\SOFTWARE\Policies\Google\Chrome\ExtensionSettings\ddkjiahejlhfcafbddmgiahcphecmpfh and set the value to {"installation_mode":"force_installed","runtime_allowed_hosts":"*://*"}

Replace \Google\Chrome\ with \Microsoft\Edge\ in the registry paths to do the same thing for Edge

**Comment by gorhill** [comment]
I tried `runtime_allowed_hosts` back when uBOL was using `optional_host_permissions`, it didn't work. Now of course it works because uBOL uses broad host permissions by default, there is no need for user gesture.

**Comment by lawndoc** [comment]
Thanks for the clarification, and sorry for the added work needed to clean that up!
