### ISSUE TITLE
any keepass password form fill extensions unable to connect to api when ublockoriginlite is enabled

### ISSUE THREAD

**Issue by TokcDK** [uBlockOrigin/uBOL-home#117]
Keepass-http-connector says unable to connect to database. Same with any other browser extensions for keepass when OBOlite is enabled. I see comment about the issue on UBOlite chrome store page from october 2022.

**Comment by gwarser** [comment]
Do you have "Block Outsider Intrusion into LAN" list enabled?

**Comment by TokcDK** [comment]
> Do you have "Block Outsider Intrusion into LAN" list enabled?

It seems so. The list was enabled but it is surprise that some enabled list is breaking work of other extensions.

I tried to search here in issues and didnt found any before.

**Comment by gorhill** [comment]
As per dev tools console, what requests from keepass password are being blocked?
