### ISSUE TITLE
Social widget 

### ISSUE THREAD

**Issue by Jokopentil** [uBlockOrigin/uBOL-home#121]
![Screenshot_2024-04-11-09-22-51-99_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/uBlockOrigin/uBOL-home/assets/114223791/a3d68289-00da-402f-a557-1197fb99a534)

![Screenshot_2024-04-11-09-22-36-33_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/uBlockOrigin/uBOL-home/assets/114223791/503fa8de-e1d9-4889-8136-625bd26803ce)

**Comment by Jokopentil** [comment]
![IMG_20240411_092814.jpg](https://github.com/uBlockOrigin/uBOL-home/assets/114223791/61d1417e-dfc0-4c38-bd88-6f771bf9fad3)

**Comment by Jokopentil** [comment]
Scroll

**Comment by Jokopentil** [comment]
https://rejogja.republika.co.id/berita/sboz2k432/bermacam-atraksi-seni-budaya-akan-digelar-di-banyuwangi-saat-libur-lebaran

**Comment by gorhill** [comment]
Filter issue, please report to filter list maintainers.
