### ISSUE TITLE
manifest file error, can't install add-on in ms extension store

### ISSUE THREAD

**Issue by pirateyporat** [uBlockOrigin/uBOL-home#122]
<img width="840" alt="Annotation 2024-04-14 000343" src="https://github.com/uBlockOrigin/uBOL-home/assets/12477036/b5a042e1-d41f-4d94-99d2-7fb4be9b5912">

**Comment by gwarser** [comment]
Successfully installed 2024.3.30.1062 right now.

Server/network issue? Clear browser cache and try again?

**Comment by gorhill** [comment]
The browser installs uBOL, uBOL doesn't install itself. This is a browser message, you need to seek support from the browser.
