### ISSUE TITLE
Performance of UBOL decreased significantly on Chromium 124

### ISSUE THREAD

**Issue by iahung3** [uBlockOrigin/uBOL-home#123]
My browser:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
```

It's a Chromium-based browser (not Chrome itself).

UBOL decreased the performance too much. The page loading speed is so slow that I have to disable it and turn the MV2 UBO on.

**Comment by gorhill** [comment]
Performance issue must be accompanied by steps to reproduce (all details needed on my side to reproduce what triggers performance issues on your side) and performance profiling data (use browser dev tools => Performance pane), otherwise the issue will be considered as invalid.
