### ISSUE TITLE
Record the total number of blocked since installation like the MV2 UBO?

### ISSUE THREAD

**Issue by iahung3** [uBlockOrigin/uBOL-home#124]

**Comment by gorhill** [comment]
uBOL is declarative, the filters are enforced by the browser and there is no declarative-friendly API to get the number of blocked requests, except [one](https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest#event-onRuleMatchedDebug) which is available only for unpacked extensions for debugging purpose.
