### ISSUE TITLE
Google's secret plan may bring an instant end to uBOL?

### ISSUE THREAD

**Issue by highbaser** [uBlockOrigin/uBOL-home#129]
So basically Google is phasing out ManifestV2 support a month from now (June 2024). This will result in the automatic disabling of all ManifestV2 extensions, including uBlock Origin, which will immediately result in Google getting lots of ad revenue as tens of millions of computers will start playing Youtube ads. Some of the users will seek an alternative, like uBlock Origin Lite, and turn that on for Youtube. However uBlock Origin Lite doesn't fetch external lists but each version contains the network filters and trusted replace JS scripts. Like the one below.
https://github.com/uBlockOrigin/uBOL-home/blob/b395c00be0101472f521b0969b790d38f5ede2b1/chromium/rulesets/scripting/scriptlet/default.trusted-replace-xhr-response.js#L45
This means as soon as ManifestV2 has been phased out, uBlock Origin instances have been already disabled in Chrome/Chromium browsers, they can introduce a rule into the Web Store ToS that the extension couldn't block ads on Google services, including Youtube. That would bring an end to uBOL as it would violate ToS, so it can't be updated with Youtube filters, nor can it fetch external filters due to restrictions. If this happens, it will mean that the whole ManifestV2->ManifestV3 transition was a plot against uBO itself.

What's your plan for a scenario like this? @gorhill ?

**Comment by loadstring1** [comment]
There is no other way than using firefox or any other browser that still supports and maintains manifest V2. Fuck google and their restrictions stop using their chromium browser and they won't get their money from tracking on their users (aka switch to firefox and protest against google once that happens)

**Comment by loadstring1** [comment]
First we need to englighten chrome users about this and somehow convince them to join this protest and switch over to firefox - thats the hard part of doing it most people will notice that firefox got better adblocking than chrome and most likely will switch and people who are clueless about adblocking will most likely stay on chrome

**Comment by minhngoc25a** [comment]
In issue [#338](https://github.com/uBlockOrigin/uBlock-issues/issues/338) of the main uBlock Origin issue tracker, gorhill posted that w3c is bringing back the ability to execute remote code again, and he closed that? It looks somehow managable (or fixed).

**Comment by krystian3w** [comment]
API agony can be extended with policies ("pretending to be a company/corporation computer"):

https://github.com/uBlockOrigin/uBlock-issues/discussions/2977#discussioncomment-9521603

**Comment by Darin755** [comment]
Honestly Ublock origin lite should be renamed to Ublock origin crippled edition or something simular. "Lite" implies that it is suppost to be lighter weight but the main purpose of the lite is to get around restrictions.

**Comment by krystian3w** [comment]
Possible back to uBo- name: https://github.com/uBlockOrigin/uBlock-issues/discussions/2261

**Comment by gorhill** [comment]
See <https://github.com/uBlockOrigin/uBlock-issues/wiki/About-Google-Chrome's-%22This-extension-may-soon-no-longer-be-supported%22>
