### ISSUE TITLE
"No filtering" feature doesn't ignore the default lists

### ISSUE THREAD

**Issue by featherbear** [uBlockOrigin/uBOL-home#131]
<img width="682" alt="image" src="https://github.com/uBlockOrigin/uBOL-home/assets/1159091/a6574866-7941-4f68-83fc-b963f8c638ef">

The "No filtering" feature (and `noFiltering` managed preference) don't allow fetch requests / XMLHttpRequests from hosts in the blocklists.

Whilst the list is intended to block trackers and metrics, it will also therefore breaks any site that uses Statsig's feature flag service.

EDIT: It seems that the `allowAllRequests` action is given if your browser visits the site, and that `allow` is given if you are sourcing a script from the site; but there is no grant for xmlhttprequest

**Comment by gorhill** [comment]
By design, "No filtering" is a filtering mode, it applies to sites you visit. If you do not want filtering when visiting `facebook.com`, it does not mean you want `facebook.com` to not be filtered everywhere else it is embedded as 3rd-party.
