### ISSUE TITLE
Control panel is inaccessible on Android

### ISSUE THREAD

**Issue by Mikaela** [uBlockOrigin/uBOL-home#133]
When I install uBlock Origin Lite on Android, the first start screen is just dark with no contents. When I enter the menu, select extensions, uBlock Origin Lite and touch settings, I get to the same dark screen with no options.

I think the extension is otherwise working as the basic site specific settings are functional.

I am mainly experiencing this on Firefox Beta 127.0b9, but reproduced this on clean Firefox Nightly 128.0a1 from FFUpdater.

My Android is version 13 (/e/OS 2.1-t-20240603406607-stable-FP5), Fairphone 5, and my languages are Finnish (Finland) and English (Finland). Both of my Firefoxes are in Finnish.

Firefox extension details report uBlock Origin Lite as version 2024.6.2.1013 last updated 5.6.2024 (today).

**Comment by gorhill** [comment]
I can reproduce.

Meanwhile, you can use "Extensions" => "Extensions Manager" => "uBlock Origin Lite" => "Settings"
