### ISSUE TITLE
[Suggestion] Separate out Adblock & Tracker lists

### ISSUE THREAD

**Issue by devashishkatoriya** [uBlockOrigin/uBOL-home#136]
Currently in uBOL settings, there is only one option "Ads, trackers, miners, and more" which blocks Ads + Trackers + Fingerprinters + Miners + others.

Would it be possible to have separate checkboxes for each of those entries? Or will it cause some regression?

Separate options would allow for configuration similar to "Very-Easy Mode" from uBO where only Ads get blocked & not the trackers. This would enable for set-&-forget type of configuration.

uBOL v2024.6.10.805
Browser: Google Chrome

**Comment by gorhill** [comment]
I prefer to leave it as is, this has been the default configuration of uBO since its inception 10 years ago.
