### ISSUE TITLE
toneto.net

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uBOL-home#139]
You need a Ukrainian VPN.

Google Chrome 126.0.6478.115

`https://toneto.net/news/tehnologii/Apple-dopomoge-nam-vibirati-komp-yuteri`

uBlock Origin Lite 2024.6.17.766

<details>
<summary>Screen</summary>

![2024-06-21_130751](https://github.com/uBlockOrigin/uBOL-home/assets/111344219/9d5a85c8-030c-489e-8713-e4eef97085a6)
![2024-06-21_131404](https://github.com/uBlockOrigin/uBOL-home/assets/111344219/7f234e05-88d0-4e85-9e96-f86c9173dbc1)
</details>

uBlock Origin 1.58.0

<details>
<summary>Screen</summary>

![2024-06-21_130832](https://github.com/uBlockOrigin/uBOL-home/assets/111344219/f56efa2b-bd87-438d-99e9-42a362d9bdd8)
![2024-06-21_130843](https://github.com/uBlockOrigin/uBOL-home/assets/111344219/d6bee077-b19c-4742-bd42-2729e5435eb6)
![2024-06-21_131501](https://github.com/uBlockOrigin/uBOL-home/assets/111344219/62023a93-0bcf-45a1-9b49-b02c35db2fb9)
</details>

**Comment by gorhill** [comment]
Somehow seems to work fine in Firefox.

**Comment by gorhill** [comment]
If I use `document_start` instead of `document_end` at [that line](https://github.com/gorhill/uBlock/blob/1.58.0/platform/mv3/extension/js/scripting-manager.js#L279), this fixes the issue.

**Comment by dportvine** [comment]
> Somehow seems to work fine in Firefox.

The author of this code does not support Firefox.
