### ISSUE TITLE
False positive for https://antizapret.prostovpn.org/proxy.pac only on Chrome and only in uBOL

### ISSUE THREAD

**Issue by ilyaigpetrov** [uBlockOrigin/uBOL-home#141]
`https://antizapret.prostovpn.org` is an anti-censorship tool for Russia.
`https://antizapret.prostovpn.org/proxy.pac` is its pac-script that returns proxies for censorship circumvention.
It also provides access on non-standard ports, e.g., `https://antizapret.prostovpn.org:8443/`.

uBOL on Chrome blocks `https://antizapret.prostovpn.org` and doesn't block it on FireFox.
I think uBOL mustn't block it. I believe it's a false positive which I report here.

**Comment by gorhill** [comment]
When I enable RUAdList, the only resource I see blocked at `https://antizapret.prostovpn.org:8443/` is `https://mc.yandex.ru/metrika/watch.js`.

Please provide more details about uBOL configuration and what exactly is being blocked as per network pane in dev tools.

**Comment by ilyaigpetrov** [comment]
Can't reproduce as of now.

**Comment by ilyaigpetrov** [comment]
@gorhill, could you, please, try with `https://antizapret.prostovpn.org/proxy.pac`. This address is blocked in Russia so I always get timeout error with or without uBOL. If you get 403 then it works as intended (blocked for non-Russian clients).

![ubol-az-popup](https://github.com/uBlockOrigin/uBOL-home/assets/1090811/95d5ba52-feef-4f28-85b6-6b3a8a54d39f)
![ubol-settings](https://github.com/uBlockOrigin/uBOL-home/assets/1090811/c76f1d7d-2d6a-4b69-91c2-c81eae75285f)
![ubol-az-timeout](https://github.com/uBlockOrigin/uBOL-home/assets/1090811/2ccaec78-35c1-46b8-a2dd-a891b1bf7ed4)

**Comment by ilyaigpetrov** [comment]
Here are all the addresses that are tried and fail with installed uBOL:
```
https://e.cen.rodeo:8443/proxy.pac
https://antizapret.prostovpn.org:8443/proxy.pac
https://antizapret.prostovpn.org:18443/proxy.pac
https://antizapret.prostovpn.org/proxy.pac
```

**Comment by ilyaigpetrov** [comment]
uBOL conflicts with my anti-censorship extension, here are the logs from it:
![ac-ubol-rcb-log](https://github.com/uBlockOrigin/uBOL-home/assets/1090811/41dd5bdc-e5f2-4f4c-a857-c39bf18fe213)

`https://gateway.pinata.cloud/ipfs/QmX5EgEy9c1vNCasj8SEwtXWbC2GvGXge4L3YjyoMh1az7/proxy-ssl.js` is blocked by client.

**Comment by Verity-Freedom** [comment]
@gorhill

**Comment by stephenhawk8054** [comment]
cc @Yuki2718
