### ISSUE TITLE
Pre-enabled rulesets in manifest.json are being disabled by `defaultRulesetsFromLanguage`

### ISSUE THREAD

**Issue by m3nadav** [uBlockOrigin/uBOL-home#143]
During the installation of the extension, the `defaultRulesetsFromLanguage` function uses a hard-coded `out` containing the default ruleset only (on ruleset-manager.js:437) so any enabled ruleset from the manifest.json that is not "default" and the language default is being disabled during installation

To fix this, that line should be 
```
const out = await dnr.getEnabledRulesets();
```

I will open a PR on this repo hoping that's the way to contribute to this version of uBO 🙏

**Comment by gorhill** [comment]
There is only one enabled ruleset by default, the `default` one.

**Comment by m3nadav** [comment]
Is there another way to control what lists are enabled that is not through the extension UI?

**Comment by m3nadav** [comment]
I just noticed I haven't given any context - I'd like to manually install the extension on multiple browsers and enable specific lists as part of the installation

The PR I opened just to manually control the enabled lists using the manifest.json file, but doesn't change the current defaults

**Comment by m3nadav** [comment]
@gorhill  I'd appreciate your comment on this
I can't open a PR to the main repository as it is limited for users that have contributed to that repository in the past
The change I propose **does not change the default filter lists**, it just uses the already declared defaults as input during the installation process, as can be seen here:
<img width="901" alt="image" src="https://github.com/user-attachments/assets/9e2ca58c-9cd5-4b7c-9b13-91be7243a3f9">

Appreciate your work, and hope to be able to contribute to it

**Comment by sissbruecker** [comment]
I'm using uBOL in an automated / headless scenario, where users never get to interact with the browser UI and thus can not modify the rulesets. I'd also like to be able to configure the default rulesets through `manifest.json`, or some other mechanism if patching `manifest.json` is not appropriate.

**Comment by m3nadav** [comment]
@sissbruecker sadly the fix [PR](https://github.com/uBlockOrigin/uBOL-home/pull/144) was denied a few days ago without any comment or reference so I'm not sure why

**Comment by gorhill** [comment]
Fixed with <https://github.com/gorhill/uBlock/commit/2782b16ecf4e25414ca1b27a144535676a764740>.
