### ISSUE TITLE
Filter list equivalency with `uAssets` lists between MV2 uBO and uBO Lite?

### ISSUE THREAD

**Issue by Hrxn** [uBlockOrigin/uBOL-home#149]
Had to search around for a while, but I think I've found the relevant part here:
https://github.com/uBlockOrigin/uBOL-home/wiki/Frequently-asked-questions-(FAQ)#when-do-filter-lists-update

So there are no filter lists at all in uBOL, at least not in the "traditional" sense. Only declarative rulesets, which have to be compiled, and then are only shipped with new versions of uBOL itself, right?

But what exactly gets compiled for uBOL -  in its settings, there is only one "filter list" entry under *Default*, what is the source for that?

Is it the entirety of the filters from https://github.com/uBlockOrigin/uAssets?

For example, I was using `filters/annoyances-cookies.txt` with uBO classic, is this (entire) list part of the defaults in uBOL?

I was asking because there's a site that is not working anymore in uBOL like it used to before and I wanted to investigate the reasons..

**Comment by garry-ut99** [comment]
> For example, I was using `filters/annoyances-cookies.txt` with uBO classic, is this (entire) list part of the defaults in uBOL?

Yes, by looking at the log: https://github.com/uBlockOrigin/uBOL-home/blob/main/firefox/log.txt , it shows that it's included:
" Fetched local  `https://ublockorigin.github.io/uAssets/filters/annoyances-cookies.txt` "

```
============================
Listset for 'annoyances-cookies':
	Fetched local https://ublockorigin.github.io/uAssets/filters/annoyances-cookies.txt
	Fetched local https://ublockorigin.github.io/uAssets/thirdparties/easylist-cookies.txt
Input filter count: 1920
	Accepted filter count: 1920
	Rejected filter count: 0
Output rule count: 1601
	Plain good: 1599

	Maybe good (regexes): 1
	redirect=: 0
	removeparams= (accepted/discarded): 0/0
	modifyHeaders=: 0
	Unsupported: 1
		Incompatible with DNR: ||clickio.mgr.consensu.org^$script,redirect-rule=noop.js,domain=mdn.lol
CSS-generic: 16928 plain CSS selectors
CSS-generic-high: 351 plain CSS selectors
CSS-specific: 6030 distinct filters
	Combined into 17734 distinct hostnames
	Combined into 3 distinct entities
CSS-declarative: 60 distinct filters
	Combined into 5456 distinct hostnames
	Combined into 2 distinct entities
Procedural-related distinct filters: 28 distinct combined selectors
	Combined into 42 distinct hostnames
	Combined into 2 distinct entities
============================
```

**Comment by gorhill** [comment]
See <https://github.com/uBlockOrigin/uBlock-issues/wiki/About-Google-Chrome's-%22This-extension-may-soon-no-longer-be-supported%22>

**Comment by Hrxn** [comment]
> > But what exactly gets compiled for uBOL - in its settings, there is only one "filter list" entry under Default, what is the source for that?
> 
> Search the log to find which filter lists are fetched into uBOL:
> 

Ah, thank you, good to know. Not really obvious to find, though 😃 
 
> Not all filters are compatible with uBOL:
> 
> * https://github.com/uBlockOrigin/uBOL-home/wiki/Frequently-asked-questions-(FAQ)#filtering-capabilities-which-cant-be-ported-to-mv3
> * similiar to: [Same filters and diff extensions but diff results, why? uAssets#24340](https://github.com/uBlockOrigin/uAssets/discussions/24340)

Understood. I think the filter in question doesn't seem to be one mentioned in the list there, implying that it *should* work in uBOL. FWIW, it's `+js(set-local-storage-item, allowCookies, true)`



<br><br>


> See https://github.com/uBlockOrigin/uBlock-issues/wiki/About-Google-Chrome's-%22This-extension-may-soon-no-longer-be-supported%22

Huh? I'm aware, I've read all these FAQs and stuff. This is a question about uBOL, if that is what was unclear here?

Oh, wait. I think I've just found the culprit.
The site that's not working anymore has been removed from `filters/annoyances-cookies.txt`

Apparently it has been moved to `thirdparties/easylist/easylist-cookies.txt`?
What is the purpose of that move?

The list just mentions this:
```
! Description: Filters optimized for uBlock Origin, to be used with EasyList's and/or Adguard's "Cookie Notices" list(s)
```

So, to get this with uBOL, I have to *additionally* select `EasyList/uBO – Cookie Notices` under `Annoyances`, right?
