### ISSUE TITLE
Please add a fourth mode - "No filtering".

### ISSUE THREAD

**Issue by 599px** [uBlockOrigin/uBOL-home#150]
uBlock Origin Lite has only three modes: Basic, Optimal, Full.
Please add a fourth mode - "No filtering".

In this mode, uBlock Origin Lite should be active but not perform any filtering, allowing manual activation for specific sites.

For example, I want it to work only on YouTube and a few other sites, and do nothing on others.

**Comment by garry-ut99** [comment]
The whole idea of "disable for all websites, and only enable for specific websites" mode, was requested many times in the past, and was always declined:
- (05.2016) https://github.com/gorhill/uBlock/issues/1623
- (11.2017) https://github.com/gorhill/uBlock/issues/3202
- (05.2019) https://github.com/uBlockOrigin/uBlock-issues/issues/586
- (03.2011) https://github.com/uBlockOrigin/uBlock-issues/issues/1534

The answer for "why declined" was provided in the following comments:
- https://github.com/uBlockOrigin/uBlock-issues/issues/586#issuecomment-494021002
- https://github.com/uBlockOrigin/uBlock-issues/issues/1534#issuecomment-803583925

Then the answer was put into the Wiki documentation:
- https://github.com/gorhill/uBlock/wiki/How-to-mark-a-web-site-as-trusted#disabling-filtering-by-default

<hr>

Though as seen, there is a workaround available in uBlock Origin, to disable uBO on all websites, and enable only on specific ones, which is a bit cumbersome, but works as expected: 
- a special regex, in which you manually put only blocked sites
- "Disable cosmetic filtering" in settings + and then using Per site switches to enable only on specific websites: 
https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering.

But none of these work in uBlock Lite: no regex support in "No filtering" area + no Per site switches available.

**Comment by gorhill** [comment]
You can enable that sort of mode by entering `all-urls` in the "No filtering" text area. This is as far as I will to support that special mode, i.e. I won't further modify the user interface.

**Comment by 599px** [comment]
[garry-ut99](https://github.com/garry-ut99) Thank you very much for such a detailed answer!!!
To be honest, I’m very upset and surprised at the same time o_O

[gorhill](https://github.com/gorhill) uBlock Origin Lite is the perfect ad blocking add-on. It doesn't require additional permissions and that's great!

Please add the ability to set the default “no filtering” mode in the settings

**Comment by gorhill** [comment]
> You can enable that sort of mode by entering `all-urls` in the "No filtering" text area.

**Comment by 599px** [comment]
[gorhill](https://github.com/gorhill)

Oh thank you so much!!! exactly what is needed!
I didn’t understand you correctly the first time, I thought I should just write all my sites list there :D

but now I only entered `all-urls` there and it turned out what I wanted!

Thanks again :)

**Comment by garry-ut99** [comment]
Worth to add, that nowhere was it publicly mentioned / documented before (either on purpose, or overlooked, or lack of time).

**Comment by gorhill** [comment]
This became possible with [this commit](https://github.com/gorhill/uBlock/commit/8616b395b2). I can't remember what led me to make this change.

**Comment by athrunsun** [comment]
@999px excuse me, but how do you make this extension to only filter ads on specific sites after entering "no filtering" mode?

**Comment by 999px** [comment]
@athrunsun 

After you have disabled filtering
Just find the desired site and set the filtering mode to "Basic".

For YouTube - to let the ad through, you need to:
- select "Optimal"
- when you select "Optimal", the browser will ask you to give permission for YouTube. give permission.
- Then reload the page (F5)
- and see that "Optimal" is not selected, since there was no permission before, but now there is. Therefore, select "Optimal" again and it will be saved.

If you select Basic, it is selected immediately, but for Optimal you need to repeat the action twice.

**Comment by gorhill** [comment]
> If you select Basic, it is selected immediately, but for Optimal you need to repeat the action twice.

That shouldn't be the case, the page should automatically reload and _Optimal_ should be immediately enforced. There was a fix related to such issue two versions ago: <ttps://github.com/uBlockOrigin/uBOL-home/releases/tag/uBOLite_2025.2.23.1382>

**Comment by athrunsun** [comment]
@999px It's working! Thank you so much!

@gorhill So uBOL added those sites where I changed mode to "basic" or "optimal" to a hidden (not visible in uBOL settings page) exception list right?
