### ISSUE TITLE
Raise minimum Firefox version to 128 after October 1st

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBOL-home#165]
Just a reminder for the future.

As per [calendar](https://whattrainisitnow.com/calendar/), Firefox ESR 128 will be the only ESR being maintained.

Firefox 128 supports `MAIN` world in [scripting.RegisteredContentScript](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/RegisteredContentScript). This simplifies uBOL's code base as the workaround specific to Firefox can then be removed.

The documentation page appears to not be up to date since I did test that the scriptlets are properly executing in `MAIN` world after removing the workaround.

**Comment by krystian3w** [comment]
https://old.reddit.com/r/firefox/comments/1de7bu1/comment/l8gcjth/

They are just running out of time to determine what the extended of support for Windows 7, 8, and 8.1 will involve. If the developers are not working on adding the removed if-s and errors specific to Windows 7, 8 and 8.1, then at most we will see 115.16.x-115.37.x releases with their use blocked on Windows 10 and 11 (at the installer level or even in the executable file "Firefox.exe").
