### ISSUE TITLE
eurointegration.com.ua: ads

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uBOL-home#166]
Open this link in a new tab https://www.eurointegration.com.ua/news/2024/08/5/7191539/
Wait 10 seconds and click on the tab, the empty space at the top is not hidden. In uBOL i see ads. You need clear cache after reload page.

Google Chrome 127.0.6533.89, uBOL 2024.8.5.925

<details>
<summary>Video uBOL</summary>

https://github.com/user-attachments/assets/5dab6a0a-84bb-43d4-9153-abf0053e3316
</details>

Also https://github.com/uBlockOrigin/uAssets/issues/24781

**Comment by gorhill** [comment]
Just lowering the filtering mode to _Basic_/_Optimal_ then back to _Complete_ causes the ads to show up afterward, but then, not always. 
Looks like a timing issue, this needs more investigation.

**Comment by stephenhawk8054** [comment]
This site looks like related to ad-shield so there might be some side-effects with the filters related to it.

**Comment by gorhill** [comment]
It's definitely a timing issue, oftentimes the target script won't be found in the DOM, hence its `onerror` handler can't be removed.

The only way I found to address the issue is to instead use a filter based on `ra,js` script, along with some modification to the scriptlet to allow for "remove attribute asap":

    eurointegration.com.ua##+js(ra, onerror, script[onerror*="error-report.com"], asap stay)

When `asap` is present, the scriptlet will not only find the target element immediately upon injection, but also immediately when the mutation observer is triggered. This result in much more reliable result, though sometimes a placeholder can be left at the top -- possibly addressable with a cosmetic filter.

**Comment by gorhill** [comment]
Solution has been to improve `ra.js` to make it possible to remove attribute without delay when DOM changes are detected, and to add a filter using `ra.js` as a reliable replacement for the procedural cosmetic filter `##script[onerror*="error-report.com"]:watch-attr(onerror):remove-attr(onerror)`.

I have verified that I could not reproduce the issue with the new `ra.js` filter.

**Comment by stephenhawk8054** [comment]
cc @JobcenterTycoon 

For some ad-shield websites in uBOL

**Comment by gorhill** [comment]
Probably that filter is also more reliable in uBO.

**Comment by stephenhawk8054** [comment]
> Probably that filter is also more reliable in uBO.

You mean this one?

```adb
##+js(ra, onerror, script[onerror*="error-report.com"], asap stay)
```

**Comment by dportvine** [comment]
> Probably that filter is also more reliable in uBO.

Yes, this scriplet works perfectly in uBO.

`eurointegration.com.ua##+js(ra, onerror, script[onerror*="error-report.com"], asap stay)`

How can I get this uBOL assembly with changes in the code?

**Comment by dportvine** [comment]
How can I get a version of uBOL with these latest changes?

**Comment by stephenhawk8054** [comment]
You have to build it yourself I think.

**Comment by gorhill** [comment]
> So, `ra.js` will not be removed eventually into the future ?

Can't remove it for now since it's the only one that can reliably remove `on...` handlers in Firefox, `remove-attr()` doesn't work because it's executed in isolated world.

**Comment by gorhill** [comment]
> How can I get a version of uBOL with these latest changes?

Is `eurointegration.com.ua` considered a high traffic site? If so, I could release a new version of uBOL.

**Comment by dportvine** [comment]
> Is `eurointegration.com.ua` considered a high traffic site? If so, I could release a new version of uBOL.

The problem is only in the new tab, the new version is not needed.

**Comment by JobcenterTycoon** [comment]
Changed here https://github.com/uBlockOrigin/uAssets/commit/bc288a8396afbd94879a6b023c5b864d1ec66583

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon I think `asap` is not available for uBO stable yet, so we might still need `:remove-attribute()` ?

**Comment by JobcenterTycoon** [comment]
Yes sorry i forgot there was a latest scriptlet change.
