### ISSUE TITLE
Deploying extension & setting default to "Complete" filtering mode

### ISSUE THREAD

**Issue by alfonsojon** [uBlockOrigin/uBOL-home#168]
Good morning, our organization currently deploys uBlock Origin to our Chromium-based browsers. Is it possible to set the default filtering mode to "Complete" while also preventing the first launch pop up? I understand if this is not due to a Manifest v3 limitation.

We are toying with the idea of instead doing strictly network-level ad blocking, but uBlock Origin gives us flexibility when a site that needs to have ads enabled needs accessed as well as quick ability to troubleshoot advertisement blocking-related issues.

Thank you!

**Comment by gorhill** [comment]
See discussion: <https://github.com/uBlockOrigin/uBOL-home/discussions/161>

**Comment by alfonsojon** [comment]
Thank you - based on my understanding, this is not currently possible & you are hoping that this feature can be addressed through browser functionality. I'll keep an eye out for any progress from the W3C, but it seems like best the immediate option is to educate our users on usage of uBlock Origin Lite.
