### ISSUE TITLE
uBlockOriginLite blocks other extension to work properly

### ISSUE THREAD

**Issue by ewoks** [uBlockOrigin/uBOL-home#169]
`uBlockOriginLite` currently (v2024.8.5.925) blocks the `TubeArchivist` Chrome extension to connect to the TubeArchivist server as described in https://github.com/tubearchivist/browser-extension/issues/44

Reducing blocking to the "Basic" or adding exception with the TubeArchivist server IP doesn't help, extension just can't connect to the server (via http if it matters).

The only workaround I came up until now so the `TubeArchivist` can connect, is to go back to `uBlockOrigin` and completely remove `uBlockOriginLite`.

Any better suggestion is welcome :)

**Comment by gorhill** [comment]
I know nothing about TubeArchivist, TubeArchivist URL or TubeArchivist API Key. What do I need to enter in the fields to reproduce the issue?

**Comment by gorhill** [comment]
> turning off _Block Outsider Intrusion into LAN_ resolves my issue

It's a browser issue, one extension is not supposed to interfere with the network requests of other extensions, see <https://github.com/w3c/webextensions/issues/369>.

As per latest comment in the thread, this is reportedly fixed in Chromium 128.
