### ISSUE TITLE
linktr.ee: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uBOL-home#173]
![image](https://github.com/user-attachments/assets/6a42324c-3a93-46c2-b8d7-7ffc25ca1510)

`https://linktr.ee/minestack`

uBlock Origin Lite 2024.8.5.925
Chrome Stable

**Comment by stephenhawk8054** [comment]
I can reproduce when refreshing while bypassing the cache in incognito.

**Comment by gorhill** [comment]
There is this filter in _Unbreak_:

    linktr.ee##+js(set, DD_LOGS, noopFunc)

What is it meant to accomplish?

I can avoid the breakage when rewriting the filter as:

    linktr.ee##+js(set, DD_LOGS, noopFunc, runAt, interactive)

**Comment by stephenhawk8054** [comment]
It's for a breakage issue when you sign in and access `https://linktr.ee/admin/settings`

**Comment by gorhill** [comment]
Does `linktr.ee##+js(set, DD_LOGS, noopFunc, runAt, interactive)` still solve the issue?

With the current filter I see exceptions reported at the console, something to do with access to `DD_LOGS.logger.info`, I don't see these errors with uBO and same filter.

![image](https://github.com/user-attachments/assets/9e09c1d9-bdc5-4e66-b9a9-0b4cfb248f61)

**Comment by stephenhawk8054** [comment]
Hmm... I think the issue is not there any more. Originally I think it's because `https://www.datadoghq-browser-agent.com/datadog-logs.js` is blocked in EP, but now they have another 1p script that does the same

```
https://assets.production.linktr.ee/profile-preview/latest/vendors-node_modules_datadog_browser-logs_esm_entries_main_js-node_modules_linktr_ee_componen-932c4a-85f5292ddb690f7d69af.js
```

so I think the filter can be removed now.

**Comment by gorhill** [comment]
Right, can't reproduce with latest lists.
