### ISSUE TITLE
aws.amazon.com: breakage

### ISSUE THREAD

**Issue by chesha1** [uBlockOrigin/uBOL-home#187]
URL: 
`https://aws.amazon.com/cn/products/`

Many requests with contents are block by uBOL.

<img width="890" alt="image" src="https://github.com/user-attachments/assets/5e1f9366-efd5-40ae-be3a-d801127c39e6">

<img width="689" alt="image" src="https://github.com/user-attachments/assets/e10c77ca-3785-47f9-9715-f0b58d11da57">

When turning off uBOL, contents are loaded successfully.

Enviroment: Chrome 127.0.6533.120, uBlock Origin Lite 2024.8.12.902

uBOL settings: basic blocking mode, all other settings are default

**Comment by stephenhawk8054** [comment]
@gorhill There's a `removeparam` filter without value

```adb
||amazonwebservicesinc.tt.omtrdc.net/m2/amazonwebservicesinc/ubox/raw$xhr,3p,removeparam,domain=aws.amazon.com
```

from this issue: https://github.com/uBlockOrigin/uAssets/issues/21446

Could it cause issue with DNR?

**Comment by gorhill** [comment]
Fixed in [uBOLite_2024.8.21.996](https://github.com/uBlockOrigin/uBOL-home/releases/tag/uBOLite_2024.8.21.996)
