### ISSUE TITLE
tiktok.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uBOL-home#188]
![image](https://github.com/user-attachments/assets/fea0fa60-64e9-43c8-a364-473edfe558f5)

Chrome Stable
uBOL: 2024.8.21.996

url:
https://www.tiktok.com/@ngisitroli/video/7374377158606736646?_r=1&_t=8njaYCQcjf3

**Comment by stephenhawk8054** [comment]
This might depend on the accounts. I turned off all extensions but still can't see the ads

![image](https://github.com/user-attachments/assets/89b60436-8db3-4ab2-8310-fbe8d5e4c7b6)

**Comment by 3xploiton3** [comment]
you right, 

i tried chrome guest mode, no ads appeared

**Comment by 3xploiton3** [comment]
> Did you try also on uBO, to determine whether ads appear only on uBOL or on both uBO & uBOL, if the latter case, then the issue can be moved to uAssets, also might be related to:
> 
> * [tiktok.com: ads uAssets#23348](https://github.com/uBlockOrigin/uAssets/issues/23348)

appear only on uBOL,

this screenshot from uBO
![image](https://github.com/user-attachments/assets/3ff1b747-e36c-4417-8285-872677255a81)

**Comment by gorhill** [comment]
What is your default blocking mode?

**Comment by 3xploiton3** [comment]
Complete mode,

![image](https://github.com/user-attachments/assets/e2f47548-31bb-40ba-b8c7-2a9d1e314804)
![image](https://github.com/user-attachments/assets/9ec806f6-5007-423b-83bb-1f542d4ee97c)



https://logpaste.com/nHphvLfU

**Comment by stephenhawk8054** [comment]
@gorhill There are these filters in `uBlock filters – Ads`

```adb
#@#.banner-ads
##.banner-ads:not(.textads)
```

Could it affect uBOL?

**Comment by gorhill** [comment]
Generic exceptions are not supported yet. I do see the filter `.banner-ads:not(.textads)` in `rulesets/scripting/generic/default.js`, however when I load the page into uBO, I also see filter to disable generic filtering, `@@||tiktok.com^$generichide`. So that would be the issue, uBOL does support disabling generic cosmetic filtering.

**Comment by stephenhawk8054** [comment]
Ah right, I didn't realize there's ghide.

I think it can be handled by EL.

cc @Yuki2718
