### ISSUE TITLE
startribune.com: nuisance

### ISSUE THREAD

**Issue by endocrine7132** [uBlockOrigin/uBOL-home#192]
Using the latest uBOL release (8.21) while navigating to a Star Tribune news article (ex:https://www.startribune.com/punishing-heat-monday-perfect-mn-state-fair-weather-follows/601131073) and a pop-up occurs at the bottom of the page blocking scrolling. This occurs while using the latest stable release of Chrome.

This pop-up does not occur while using uBlock Origin proper on Firefox or Chromium-based browsers. Is this pop-up an example of the inherent limitations of mv3 blockers (as noted in the FAQ regarding anti-adblock limits) or is this a filter list issue or an issue with DNR rules?

**Comment by stephenhawk8054** [comment]
Can you screenshot your uBOL settings?

**Comment by gorhill** [comment]
Also a screenshot of the page with the "popup" would be helpful. I see a banner overlay at the bottom, but it does not stop scrolling, and also occurs with uBO.

**Comment by endocrine7132** [comment]
Attached are the requested screenshots of my settings and of the page (screen pop-up at the bottom of the capture). I did test further on my end, and it appears that the reason I was not seeing the pop-up on my personal devices was due to using a NextDNS profile w/Hagezi Pro++ enabled. A domain within that list must be blocked by the DNS list, but is not blocked by uBO/uBOL. When I switched to using a non-filtering DNS service, the pop-up was present. When I try and scroll with the pop-up present, it prevents me from doing so on my end. It appears this is more likely a filter issue than an issue with uBOL. My apologies for the possible confusion on my part.

![Screenshot 2024-08-26 2 49 34 PM](https://github.com/user-attachments/assets/e555444c-5a22-4f5d-92b9-427c4e2f5b5f)
![Screenshot 2024-08-26 2 47 56 PM](https://github.com/user-attachments/assets/471fdc89-0a37-40fe-a400-dfb9d5bee228)

**Comment by garry-ut99** [comment]
> and a pop-up occurs at the bottom of the page blocking scrolling.
> When I try and scroll with the pop-up present, it prevents me from doing so on my end.
> It appears this is more likely a filter issue than an issue with uBOL.

Just like https://github.com/uBlockOrigin/uBOL-home/issues/192#issuecomment-2310430850, the popup appears, but I'm unable to reproduce broken scroll bar with your settings, neither on uBO, nor on uBOL.

<hr>

> A domain within that list must be blocked by the DNS list, but is not blocked by uBO/uBOL. 

By the way, a hint - to block the popup in uBOL (without Hagezi): with "_Steven Black’s Unified Hosts (adware + malware)_" list enabled, the popup doesn't appear.

**Comment by endocrine7132** [comment]
> By the way, a hint - to block the popup in uBOL (without Hagezi): with "_Steven Black’s Unified Hosts (adware + malware)_" list enabled, the popup doesn't appear.
Thank you for the tip, that does indeed appear to have solved the issue. Apologies for taking up valuable time with what turned out to be a user error on my part. Thank you for your assistance!
