### ISSUE TITLE
Ublock origin lite for Microsoft Edge Chromium is two versions behind. 

### ISSUE THREAD

**Issue by ThiliChanu** [uBlockOrigin/uBOL-home#196]
Ublock origin lite for Microsoft Edge Chromium is two versions behind. Have you abandoned the support for Microsoft Edge Chromium of Ublock Origin Lite? Is this the reason for no updates?

**Comment by gorhill** [comment]
How fast Microsoft Edge Addons approves submitted new version is out of my control. Please provide feedback to Microsoft Edge Addons.

**Comment by gorhill** [comment]
For reference:

![image](https://github.com/user-attachments/assets/9a5ea787-c73a-4a9c-b20d-1995019dc405)

The statement _"Expect to hear back from us in 7 business days"_ is invalid, this is a common occurrence that a submitted version languish _in review_ way past 7 days, including versions that never cleared _in review_ before a new version was submitted.

**Comment by ThiliChanu** [comment]
> How fast Microsoft Edge Addons approves submitted new versions is out of my control. Please provide feedback to Microsoft Edge Addons.

If that is the case why is it not affecting on other extensions? I noticed this exclusively with ublock origin lite. Earlier I noticed the same with ublock origin. At that time i thought it was due to 3rd party uploader. (please transfer that extension to your Microsoft uploader account via transfer process of Microsoft. 3rd party uploader is always delaying updates) As the creator of the extension what was the official response you got from officials at Microsoft about this problem?

**Comment by stephenhawk8054** [comment]
> If that is the case why is it not affecting on other extensions?

You need to ask Microsoft Edge Add-ons dev about this. How can uBO dev know why? They are the ones reviewing each extension, only they know what are the differences between each extension, not uBO dev.

They said it clearly in the screenshot above:

```
Microsoft is reviewing your submission currently. Expect to hear us in 7 business days.
```

If they don't provide any feedbacks, how can uBO dev "hear" anything from them?

**Comment by garry-ut99** [comment]
> ThiliChanu, EranAtty 

Don't spam, search issue tracker (and if you did it, do it better next time), a duplicate of:
- https://github.com/uBlockOrigin/uBOL-home/issues/101
- https://github.com/uBlockOrigin/uBOL-home/issues/25#issuecomment-1917007558

<hr>

> gorhill : https://github.com/uBlockOrigin/uBOL-home/issues/196#issuecomment-2329682569 : Reference: (screenshoot)

Also previous by the way: 
- https://github.com/uBlockOrigin/uBOL-home/issues/25#issuecomment-1917007558

<hr>

Besides, uBOL can be installed from Chrome Web Store, it works in Edge:
- https://github.com/uBlockOrigin/uBOL-home/issues/25#issuecomment-1410875693
- https://github.com/nicole-ashley/uBlock-Edge/issues/134#issuecomment-608668471

**Comment by EranAtty** [comment]
> For reference:
> 
> ![image](https://private-user-images.githubusercontent.com/585534/364490893-9a5ea787-c73a-4a9c-b20d-1995019dc405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjcyODksIm5iZiI6MTcyNTUyNjk4OSwicGF0aCI6Ii81ODU1MzQvMzY0NDkwODkzLTlhNWVhNzg3LWM3M2EtNGE5Yy1iMjBkLTE5OTUwMTlkYzQwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwOTAzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjA0ZGYxN2IwMzgxNDIzZjI5NjY3ZjE0NWI4MmJjZGRiYjA1MjExZTEyOGY5NmM2N2QyN2I3N2Q5OGNhNDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tHggOiu3FFTFsKztwcRTjqtocZptdsFfmkqwg1Im4rM)
> 
> The statement _"Expect to hear back from us in 7 business days"_ is invalid, this is a common occurrence that a submitted version languish _in review_ way past 7 days, including versions that never cleared _in review_ before a new version was submitted.

If your submissions getting delayed in the review process for thia much long it has to be a compatibility issue like copy and paste it from Chrome as it is. As op said this is only happening with ublock origin lite right now which is a developer issue than Microsoft issue.

**Comment by stephenhawk8054** [comment]
How do you know it's just uBOL?

That message occurs very frequently for different extensions. It depends on Microsoft's server, dev has no controls how they work: https://github.com/microsoft/MicrosoftEdge-Extensions/issues/58

Just because you don't see it happening with other extensions you know right now, doesn't mean that the issue is from extension dev.

**Comment by garry-ut99** [comment]
Some users mentioned that they needed to wait 14 or 10 days:
- https://github.com/microsoft/MicrosoftEdge-Extensions/discussions/46#discussioncomment-9004310
- https://github.com/microsoft/MicrosoftEdge-Extensions/discussions/114#discussioncomment-10501497

**Comment by stephenhawk8054** [comment]
How are you sure Microsoft has maximum days for review?

**Comment by garry-ut99** [comment]
> ThiliChanu :  It has been more than 14 days for the previous update. (not the latest version. The previous one) It wasn't there on the extension store. Hence that argument doesn't make any sense.

The previous one is `2024.8.21.996`, "that argument doesn't make any sense" because it was released 15 days ago, and not 14? Congratulations, you've caught me on day 1 difference, just because I trusted recklessly the github label "2 weeks ago" (and forgot about that it's just a label): 
<img src="https://github.com/user-attachments/assets/a6ff05bd-db8e-46e2-9f8d-af41729ae4c7" width=70%>

Unless you meant that that `2024.8.21.996` was updated (appeared) after more than 14 days, then good to know, as I didn't know that, as I don't use uBOL nor Edge, means I don't spy/study it's release history, nor I looked into [Wayback Machine](https://archive.org/) so far.

<hr>

Anyway, it seems uBOL Edge `2024.9.1.1266` has finally appeared jsut right now on Edge Store: 
https://microsoftedge.microsoft.com/addons/detail/ublock-origin-lite/cimighlppcgcoapaliogpjjdehbnofhn

**Comment by ThiliChanu** [comment]
> > which is a developer issue than Microsoft issue
> 
> There is no point speculating -- if there was something wrong with the extension, it would be conveyed to me. It is not, and it is not the first time it languishes in review, it happened in the past and there were never feedback about something being wrong, and the extension _was_ eventually cleared for publication out of the blue.
> 
> I shared all the information I am aware of regarding the issue. If people do not believe I am truthful with my explanation then it means they do not trust me. As I have often repeated, do not install extensions from untrusted sources, so probably best to just remove uBOL and find something else you trust.

When you said do not install extensions from untrusted sources a similar thing happing even with the legit sources like chrome store. Most people install ublock insted of ublock origin or ublock origin lite. This has been a problem because we had to train new it guys otherwise they install the wrong extension. That is true that king of things always happens.

**Comment by ThiliChanu** [comment]
> > ThiliChanu :  It has been more than 14 days for the previous update. (not the latest version. The previous one) It wasn't there on the extension store. Hence that argument doesn't make any sense.
> 
> The previous one is `2024.8.21.996`, "that argument doesn't make any sense" because it was released 15 days ago, and not 14? Congratulations, you've caught me on 1 day difference, just because I trusted recklessly the github label "2 weeks ago" (and forgot about that it's just a label): <img alt="" width="70%" src="https://private-user-images.githubusercontent.com/72945564/364797814-a6ff05bd-db8e-46e2-9f8d-af41729ae4c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTAzMjYsIm5iZiI6MTcyNTU1MDAyNiwicGF0aCI6Ii83Mjk0NTU2NC8zNjQ3OTc4MTQtYTZmZjA1YmQtZGI4ZS00NmUyLTlmOGQtYWY0MTcyOWFlNGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE1MjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZTI0ZGM1MWQzMjllZjZmMTRlYTliZmUyMzcyMzMxMzhlZGNmYTI5M2Q2Yjg4OTQ1OGViMTM0MWZjNWU3MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49eFuOVyduK2oeHP-uujn2QrCm9cfNJz1tE9GV-KJ-0"> Not to mention that 10 and 14 days were examples, and there also can exist longer cases than 14 days, but not reported.
> 
> Unless you meant that that `2024.8.21.996` was updated (appeared on Edge Store) after more than 14 days, then good to know, as I didn't know that, as I don't use uBOL nor Edge, means I don't spy/study it's release history, nor I looked into [Wayback Machine](https://archive.org/) so far. Also I'm aware of [#25 (comment)](https://github.com/uBlockOrigin/uBOL-home/issues/25#issuecomment-1917007558) mentioned longer than 14 days.
> 
> Anyway, uBOL Edge `2024.9.1.1266` has finally appeared just right now on Edge Store: [LINK](https://microsoftedge.microsoft.com/addons/detail/ublock-origin-lite/cimighlppcgcoapaliogpjjdehbnofhn)

Why you keep attacking a person who pointed out a misinformation as a misinform. It has been more that 14 day and that version was not there. Just few minutes ago that other update came which was the latest version. So what that person was pointed was correct.

**Comment by garry-ut99** [comment]
I don't attack anyone, it's just your wrong imagination, it's rather you who is attacking me, you seem to be very agressive toward me, but I will take that as potentially a language barrier. Keep arguing for the sake of arguing that there is so huge difference between 14 and 15 days.

**Comment by stephenhawk8054** [comment]
What that person pointed was:

> As op said this is only happening with ublock origin lite right now **which is a developer issue than Microsoft issue**.

And yet here we see Microsoft just approved the extension **without the developer changing anything**. That proves the statement is not correct.

**Comment by gorhill** [comment]
Please keep focus on the topic at hand.

Over arguing just make everything difficult for everybody and does nothing to resolve issues. There is no award given for whoever has the last word.

My first comment should have been enough to address the issue, i.e. all is in the hands of Microsoft Edge Addons, there is nothing I can do. If this is deemed not sufficient, then this is a trust issue, which is not a uBOL issue, it's a personal opinion issue which is not something I can solve.

Let's leave it at that.

**Comment by ThiliChanu** [comment]
> What that person pointed was:
> 
> > As op said this is only happening with ublock origin lite right now **which is a developer issue than Microsoft issue**.
> 
> And yet here we see Microsoft just approved the extension **without the developer changing anything**. That proves the statement is not correct.

Still telling us that 14 days thing mentioned above is true?

**Comment by EranAtty** [comment]
> > What that person pointed was:
> > > As op said this is only happening with ublock origin lite right now **which is a developer issue than Microsoft issue**.
> > 
> > 
> > And yet here we see Microsoft just approved the extension **without the developer changing anything**. That proves the statement is not correct.
> 
> Still telling us that 14 days thing mentioned above is true?

Yeah. Can't understand why keep defending it.
