### ISSUE TITLE
Transparent/gray box at the bottom of the page

### ISSUE THREAD

**Issue by hugok79** [uBlockOrigin/uBOL-home#200]
uBlock Origin Lite 2024.9.1.1266

Transparent/gray box at the bottom of the page in DistroWatch.com

![Captura de ecrã 2024-09-07 104101](https://github.com/user-attachments/assets/6e3d0c78-165a-41e0-adf0-ce828a120282)

**Comment by stephenhawk8054** [comment]
Please always give exact URL where you see the issue. Don't make others type one-by-one character from the screenshots.

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. Which uBOL version are you using? Can you screenshot your uBOL settings?

**Comment by hugok79** [comment]
uBlock Origin Lite 2024.9.1.1266

The country is Portugal

**Comment by stephenhawk8054** [comment]
> Can you screenshot your uBOL settings?

**Comment by hugok79** [comment]
![Captura de ecrã 2024-09-07 113612](https://github.com/user-attachments/assets/cbbcec6b-35b8-494d-9903-b8a799cb058b)
![Captura de ecrã 2024-09-07 113709](https://github.com/user-attachments/assets/f440332d-a3ab-4fee-857d-dbb67bdcb3b9)
![Captura de ecrã 2024-09-07 113821](https://github.com/user-attachments/assets/664a645e-e82c-41dd-90a9-11ec0af6769c)

**Comment by stephenhawk8054** [comment]
In the website that has issue, does the issue still occur if you click on uBOL icon and drag the slider to `Optimal` or `Complete` mode?

**Comment by hugok79** [comment]
In `Complete` mode it disappears !!

![Captura de ecrã 2024-09-07 122451](https://github.com/user-attachments/assets/31957b80-d9f4-4b01-9f22-bc0047c47bf2)

**Comment by gorhill** [comment]
That is the solution in general: if a site is broken in any given mode, try other modes to find out if this solves the issue.
