### ISSUE TITLE
okdiario.com: breakage

### ISSUE THREAD

**Issue by Darthmicowars** [uBlockOrigin/uBOL-home#204]
Activated Easylist _Spanish_ filters and Adguard _Spanish_ filters (by default uBoL activates these filters if you install it in a Spanish language browser.)

uBOL blocks articles from this newspaper using `Complete mode and Optimal mode`.

I have tested and see that the **Adguard Spanish filter** is possibly causing the issue. I have reported the problem to the Adguard team but it seems that some specific uBOL configuration is causing it because when I install Adguard MV3 beta for Chrome there is no such issue.

**Comment by gorhill** [comment]
Same issue as the one discussed in <https://github.com/uBlockOrigin/uBOL-home/issues/202#issuecomment-2340637577>, i.e. specific exceptions are discarded.

However I see the following filters in AdGuard Spanish:

    okdiario.com##.ad-slot-ph
    ...
    okdiario.com#@#.ad-slot-ph

There is no point in having the first filter is it's going to be excepted in the same list. Even though there is something to fix in uBOL, it can't hurt to remove these filters which accomplish nothing in the end.

**Comment by stephenhawk8054** [comment]
cc @Yuki2718
