### ISSUE TITLE
cnn.com: ads

### ISSUE THREAD

**Issue by Kylgos** [uBlockOrigin/uBOL-home#208]
You see ads when starting videos on CNN's website (www.cnn.com). These ads last several seconds. Occurs with _Complete mode_ enabled.

An example of a video displaying an annoying full screen advertisement: https://edition.cnn.com/2024/09/23/politics/video/james-carville-mary-matalin-intv-ac360-marriage-digvid

**Comment by stephenhawk8054** [comment]
Which browser are you using?

**Comment by stephenhawk8054** [comment]
Somehow the `removeparam` filters can't be applied to this site: https://github.com/uBlockOrigin/uAssets/blob/e444ad140245d0a82d5adf54cd71ec0d6f3caa37/filters/filters-2023.txt#L3751-L3757

A workaround may be using `uritransform`:

```adb
||warnermediacdn.com/csm*.m3u8^$xhr,3p,uritransform=/&(?:afid|app_csid|caid|conf_csid|prof)=[^&]+//g,domain=cnn.com
```

**Comment by Kylgos** [comment]
> Which browser are you using?

Google Chrome.

Thank you, it seems to be fixed now!

**Comment by stephenhawk8054** [comment]
If you are using uBOL, you'll need to wait until next version update.

**Comment by gorhill** [comment]
Confirmed fixed in latest stable release.
