### ISSUE TITLE
UBlock Origin Lite odd behaviour ?

### ISSUE THREAD

**Issue by cc2150dx** [uBlockOrigin/uBOL-home#216]
Sometimes when I click a link Chrome downloads a small 17 Byte file, when I try a second time the website loads. This issue does not exist with UBO, just the lite version.

![Screenshot 2024-09-29 200456](https://github.com/user-attachments/assets/286ea335-4cbe-4979-92f4-239abe4f9c04)

I tried to upload file here but it says "We don’t support that file type.

Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP."

**Comment by gwarser** [comment]
Do you have any other add-ons? Try turning them off.

**Comment by cc2150dx** [comment]
Same result.

**Comment by gorhill** [comment]
You will have to share more information about your configuration:

- Which rulesets are enabled?
- What is the default filtering mode?
- What is the filtering mode on `google.ca`?
- Name of other extensions

**Comment by gorhill** [comment]
Frankly I doubt this is related to uBOL, I can't think of anything in uBOL, which works through DNR rules, which would cause this. There are other cases out there of this happening:

- https://www.quora.com/Why-has-Google-Chrome-been-downloading-webpages-any-time-I-click-on-a-link
- https://support.google.com/chrome/thread/295527807/when-i-click-on-a-site-link-after-a-google-search-chrome-automatically-downloads-a-file-for-me?hl=en
- https://www.reddit.com/r/chrome/comments/73zzuo/help_please_help_chrome_keeps_downloading_files/
- https://superuser.com/questions/53136/google-search-results-are-downloaded-as-a-file-in-google-chrome

And so on.

**Comment by cc2150dx** [comment]
I found out Kaspersky Plus (antivirus) was causing the issue with Windows 11.  Thanks for the help.  On a side note UBO/L is the best, keep up the great work :) !!
