### ISSUE TITLE
Is it possible to provide the crx file?

### ISSUE THREAD

**Issue by Areire** [uBlockOrigin/uBOL-home#224]
Is it possible to add a file download for crx to the github release distribution page, it's not very convenient with a zip install. And Chrome web store is about to stop supporting mv2 extensions and may remove ublock origin from Chrome web store.

**Comment by gorhill** [comment]
I tried locally `chromium --pack-extension=./dist/build/uBlock0.chromium/` and this worked, a `.crx` was created and I could drag it to the browser for installation.

Now it's to figure how this can be done from a GitHub Actions. I found <https://github.com/browser-actions/setup-chrome> but I have to figure out what this exactly do, I wouldn't want our GitHub Actions to become too heavy, there are limits to respect for free plan.

**Comment by Nalcam** [comment]
I tried locally chromium --pack-extension=./dist/build/uBlock0.chromium/

**Comment by panty-sniffer** [comment]
@gorhill if hitting limit is the problem this belongs on [Codeberg](https://codeberg.org)
Also please consider making the CRX asap. Those of us who are using [ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium) don't want to visit or rely on chrome webstore for updates.

**Comment by xfnw** [comment]
> Given this would be useful only for Linux users, I consider it's not worth the added maintenance overhead.

would distributing crx files instead of the zip files currently in releases reduce the maintenance overhead? crx files can be used for anything that the zip files are currently being used for, since they are zip files with a little bit of extra metadata

**Comment by gorhill** [comment]
I tried to generate a CRX file, but in the end my Chromium didn't accept the drag and drop as it saw the file as a potential malware -- so it's not possible to simply drag and drop `.crx` file, hence no point generating that file.
