### ISSUE TITLE
Fix slide radius

### ISSUE THREAD

**Issue by silvaivanilto** [uBlockOrigin/uBOL-home#225]
Fix the slides radius, please, I can't send pull. It's attacking my Obsessive Compulsive Disorder.

![image](https://github.com/user-attachments/assets/7fd18923-0c71-48ac-b4be-05dd0a3ffb94)

![image](https://github.com/user-attachments/assets/3e81e223-ecb2-4e48-91a4-e84e759a6fb1)

**Comment by gorhill** [comment]
I can't accept PR based on "attacking my Obsessive Compulsive Disorder". This opens the door for endless requests to modify the look and feel based on anyone's subjective opinion.

Originally I was going for a hand-drawn look ([example](https://www.getpapercss.com/docs/components/forms/)), this is what I ended up with.
