### ISSUE TITLE
Bundled host file-based lists no longer relevant

### ISSUE THREAD

**Issue by jawz101** [uBlockOrigin/uBOL-home#227]
Steven Black & Dan Pollock lists don't produce any rules for uBO Lite

![2024-10-09_9-14-42](https://github.com/user-attachments/assets/04c6b8dc-a1a6-4e0f-b119-3e464f466a05)

**Comment by gorhill** [comment]
> don't produce any rules for uBO Lite

Open the rulesets to see the rules:

Dan Pollock: <https://github.com/uBlockOrigin/uBOL-home/blob/uBOLite_2024.10.6.1334/chromium/rulesets/main/dpollock-0.json>
Steven Black: <https://github.com/uBlockOrigin/uBOL-home/blob/uBOLite_2024.10.6.1334/chromium/rulesets/main/stevenblack-hosts.json>
