### ISSUE TITLE
Anti-Adblock Killer by reek Don't touch my Adblocker !

### ISSUE THREAD

**Issue by amidevous** [uBlockOrigin/uBOL-home#228]
please ublock origin will be removed from chrome

and ublock lite does not allow to add external filter list

please add this default filter list for all in ublock lite

among the most important lists this is the only one that is missing

https://reek.github.io/anti-adblock-killer/#filterlist

https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

thanks

svp ublock origin va être supprimer de chrome

et ublock lite ne permet pas d'ajouter de liste de filtre externe

veillez ajouter cette liste de filtre par défaut pour tous dans ublock lite

parmi les listes les plus importantes c'est la seul qui est manquante

https://reek.github.io/anti-adblock-killer/#filterlist

https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

merci

Por favor, ublock Origin se eliminará de Chrome.

y ublock lite no te permite agregar una lista de filtros externos

agregue esta lista de filtros predeterminada para todos en ublock lite

entre las listas más importantes esta es la única que falta

https://reek.github.io/anti-adblock-killer/#filterlist

https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

Gracias eres el mego

**Comment by stephenhawk8054** [comment]
That list hasn't been updated for 8 years. uBO and uBOL defuse anti-adblock by default. Report the sites by the report button.
