### ISSUE TITLE
This extension reloaded itself too frequently

### ISSUE THREAD

**Issue by physkets** [uBlockOrigin/uBOL-home#234]
uBOL was disabled by Chrome on my machine with the message: **This extension reloaded itself too frequently.**

How do I diagnose what is causing this?

**Comment by gorhill** [comment]
Try to turn on, off, then on again.

**Comment by physkets** [comment]
When that message comes up, the toggle switch to do so also disappears. It's as if chrome does not want you turning it on again.

**Comment by gorhill** [comment]
uBOL force-reload itself _once_ when it detects the browser failed to initialize it properly, see <https://github.com/uBlockOrigin/uBOL-home/issues/199>. If it happens repeatedly, I can only guess why, possibly a corrupt installation, or corrupt browser profile. See if it works in a new browser profile.

**Comment by garry-ut99** [comment]
Also:
- https://github.com/bitwarden/clients/issues/5165
- https://stackoverflow.com/questions/29086691/chrome-this-extension-loaded-itself-too-frequently
- https://www.reddit.com/r/Dashlane/comments/hngnoe/chrome_win10_this_extension_reloaded_itself_too/

**Comment by physkets** [comment]
I am unable to reproduce this issue again.

**Comment by gorhill** [comment]
I can artificial reproduce this by adding a `throw new Error();` instruction in the initialization code.

The reload of the extension was put in place to deal with instances of the browser failing inside its extensions framework once in a while. Reloading would fix this case, and the extension would write to local storage to remember that it was force-reloaded. 

However, if the error occurs in the extension code itself (which is what the `throw new Error();` mimic), it appears the local storage write operation is not working. I need to investigate for a sure way to force a reload if one was already performed.
