### ISSUE TITLE
Ad Blocking

### ISSUE THREAD

**Issue by LeventeCornea** [uBlockOrigin/uBOL-home#243]
[BugReport_Ad_Blocking_Levente_Cornea.docx](https://github.com/user-attachments/files/17611067/BugReport_Ad_Blocking_Levente_Cornea.docx)

![Screenshot 2024-11-03 175213](https://github.com/user-attachments/assets/e933f197-eb6a-4191-8fbe-a4f1d403b39f)

**Comment by gorhill** [comment]
Use the _chat_ icon in the popup panel of uBOL to report filtering issues.
