### ISSUE TITLE
GTM scripts blocked despite having the website added to the nofiltering list

### ISSUE THREAD

**Issue by ugo-zaber** [uBlockOrigin/uBOL-home#247]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality by using the _chat_ icon in the popup panel.
- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBOL-home/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO Lite in the browser.

### I tried to reproduce the issue when...

- [X] uBO Lite is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Hi,

We use GTM scripts on our websites and we noticed that even when the URL is added to the nofilter rule, the scripts are being blocked. The console gives an error "net::ERR_ABORTED 504 (Gateway Timeout)". If ublock lite is disabled, everything loads correctly. I tried whitelisting subdomains, googletagmanager.com etc ... and nothing helps.

### A specific URL where the issue occurs.

```text
https://www.zaber.com
```

### Steps to Reproduce

1. Go to https://www.zaber.com
2. Enable the developer move (F12)
3. Disable all filtering (slider all the way to the left)
4. Refresh website and witness the scripts being blocked.
5. Now disable the ublock lite entire and refresh, the scripts are now allowed

### Expected behavior

GTM shouldn't be blocked when the app is allowing trackers for unfiltered websites.

### Actual behavior

GTM scripts are blocked on whitelisted websites.

### uBO Lite version

2024.11.20.858

### Browser name and version

Google Chrome 131.0.6778.71

### Operating system and version

Windows 11 23H2

**Comment by Yuki2718** [comment]
This seems to be a serious issue. When user whitelisted a site, he and us assume ALL the requests will be allowed, this is the whole point of the whitelist.

**Comment by gorhill** [comment]
> This seems to be a serious issue

Sure, but it's a DNR issue, there is nothing I can do on my side.
