### ISSUE TITLE
Unexpected behavior on notion.so

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uBOL-home#249]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality by using the _chat_ icon in the popup panel.
- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBOL-home/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO Lite in the browser.

### I tried to reproduce the issue when...

- [X] uBO Lite is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Browsing the specified URLs I casually noticed that in the extensions screen uBlock Origin Lite had errors.

### A specific URL where the issue occurs.

```text
https://www.notion.so/notion/Terms-and-Privacy-28ffdd083dc3473e9c2da6ec011b58ac
https://www.notion.so/notion/Privacy-Policy-3468d120cf614d4c9014c09f6adc9091
```

### Steps to Reproduce

I have visited the URLs specified above.

### Expected behavior

No errors should occur.

### Actual behavior

![image](https://github.com/user-attachments/assets/d53d4e9b-10e9-4487-b313-7b9a38816200)

```adb
notion.so##+js(prevent-fetch, splunkcloud.com/services/collector)
```

### uBO Lite version

2024.11.20.858

### Browser name and version

Google Chrome 131.0.6778.86 (arm64)

### Operating system and version

macOS Sonoma 14.7.1

**Comment by gorhill** [comment]
EasyPrivacy's `||exp.notion.so^` causes the network request `https://exp.notion.so/v1/initialize` to be blocked.

All is working fine, the site is just reporting the issue at the dev console. Same would happen blocking the remote server by other mean, this is not an issue with uBOL.
