### ISSUE TITLE
Post ublock origin lite to Microsoft Edge addons store

### ISSUE THREAD

**Issue by HotCakeX** [uBlockOrigin/uBOL-home#25]
ublock origin lite which is compatible with manifest v3 is in Chrome store but not Edge addons store.
please post it in there too. Thanks
https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home

**Comment by iam-py-test** [comment]
Until it is available, you can install uBo lite from [the normal Chrome Web Store in Edge](https://chrome.google.com/webstore/detail/ddkjiahejlhfcafbddmgiahcphecmpfh). Just be sure this is enabled:
![image](https://user-images.githubusercontent.com/84232764/215850219-0e293358-9d5d-41a5-8e8f-808f23e9c564.png)
You also _should_ be able to install normal uBo either from the M$ extension store or the Chrome Web Store.

**Comment by gwarser** [comment]
Reddit thread https://www.reddit.com/r/uBlockOrigin/comments/10mnsgi/post_ublock_origin_lite_to_microsoft_edge_addons/

**Comment by Meyers07** [comment]
Really, given increasingly heavy handed Google toward blockers, somebody responsible should need to post UBOL into Edge Store. Unless you have to charge money (unlikely) it isn't that hard.

**Comment by iam-py-test** [comment]
FYI, a M$ account isn't needed to publish an extension: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/github

**Comment by gorhill** [comment]
@iam-py-test Thanks for the info, this looks realli easy, I just wonder if at any point in the process I am going to be asked to launch Edge, I don't have Windows etc. Also, need to read the 52-page _App Developer Agreement_...

**Comment by iam-py-test** [comment]
>  I don't have Windows

Edge can be used on Linux, but I have never tried it: https://www.microsoft.com/en-us/edge/download
I was able to create the partner account thing in Firefox, but no idea about uploading the actual extension.
Thanks

**Comment by gorhill** [comment]
I gave it a try and it's failing:

![image](https://github.com/uBlockOrigin/uBOL-home/assets/585534/df6d6865-51f5-4151-a649-cdf63bb2a14d)

`/rulesets/main/default.json` is present in the package:

![image](https://github.com/uBlockOrigin/uBOL-home/assets/585534/eaf32795-5b3b-4322-b510-9386fd3ed094)

**Comment by gorhill** [comment]
Alright, published to the Microsoft store, under review. I will need to spend more time on the listing later to add more language, I had to remove support for a bunch of these because it's a very long process and I ran out of time.

**Comment by HotCakeX** [comment]
@gorhill Thank you, English is good enough for now

**Comment by gorhill** [comment]
All supported languages have been added.

**Comment by gorhill** [comment]
https://microsoftedge.microsoft.com/addons/detail/ublock-origin-lite/cimighlppcgcoapaliogpjjdehbnofhn

**Comment by gorhill** [comment]
It takes forever for uBOL to clear review in the Microsoft Store. Yesterday I published 2024.1.29.1338, and while it's already available in both Firefox and Chrome web store, version 2024.1.14.912 published more than two weeks ago is still pending review in the Microsoft store (and I didn't "hear back from them" since I published)...

![Screenshot from 2024-01-30 09-25-45](https://github.com/uBlockOrigin/uBOL-home/assets/585534/eb01f795-c05f-41f0-85d9-f30c727e3318)
