### ISSUE TITLE
dzen.ru (yandex browser)

### ISSUE THREAD

**Issue by ops244** [uBlockOrigin/uBOL-home#252]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality by using the _chat_ icon in the popup panel.
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBOL-home/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO Lite in the browser.

### I tried to reproduce the issue when...

- [X] uBO Lite is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Hello, on the website dzen.ru the extension does not work

### A specific URL where the issue occurs.

```text
dzen.ru
```

### Steps to Reproduce

go to dzen.ru

### Expected behavior

....

### Actual behavior

.....

### uBO Lite version

2024.11.25.1376

### Browser name and version

yandex browser

### Operating system and version

windows 11

**Comment by gorhill** [comment]
"Does not work" is too vague. You need to describe exactly what is the issue, with screenshot if it helps.

Anyway, my understanding is that uBO is blacklisted by Yandex browser.

cc @dimisa-RUAdList

**Comment by ops244** [comment]
hi, yes, it pretends as if it is not turned on, there are no settings even
at the same time, it works fine in chrome
and the old ublock origin development build also works on dzen.ru
![2024-12-01_22-10-50](https://github.com/user-attachments/assets/c58c6ce0-fc99-4998-912e-bf1f81a24562)

**Comment by ops244** [comment]
and this is a screenshot of the old version of unlock origin development build - it works in yandex
![2024-12-01_22-14-42](https://github.com/user-attachments/assets/7497b91c-915d-49f0-acf9-ca4fa4fddc20)

**Comment by dimisa-RUAdList** [comment]
Yandex Browser is designed to spy on users and protect ads from being blocked. It does not allow blockers to run on its own or partner domains. The only blocker that was not previously on Yandex's blacklist is the dev-version of uBlock Origin. But this is more of a random feature than a planned one.

**Comment by ops244** [comment]
yes, but on the mobile version, ublock origin lite works immediately after installation, then it also falls off (but still somehow it works after installation)

**Comment by dimisa-RUAdList** [comment]
I don't check the rules in advertising browsers, it's pointless.

**Comment by gorhill** [comment]
From the screenshot, it looks like uBOL is not able to function properly in that browser.

**Comment by ops244** [comment]
I understood this, I thought maybe there is a solution like with development build...

**Comment by gorhill** [comment]
You can download and manually install from the release section: <https://github.com/uBlockOrigin/uBOL-home/releases>.

**Comment by ops244** [comment]
if you install it manually, it works! thank you!
