### ISSUE TITLE
All local resources are blocked

### ISSUE THREAD

**Issue by JonSnow88** [uBlockOrigin/uBOL-home#256]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality by using the _chat_ icon in the popup panel.
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBOL-home/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO Lite in the browser.

### I tried to reproduce the issue when...

- [X] uBO Lite is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I am unable to get to the web interface for my router, proxmox or similar resources hosted locally. Once filtering is complete turned off the web pages load without issues. 

### A specific URL where the issue occurs.

```text
any local resource
```

### Steps to Reproduce

go to router locsal resource web page 

### Expected behavior

router login screen 

### Actual behavior

blank page

### uBO Lite version

2024.12.10.932

### Browser name and version

Edge 131.0.2903.86

### Operating system and version

Windows 11 23H2

**Comment by stephenhawk8054** [comment]
Please screenshot which mode are you using and which filter lists are you enabling

**Comment by gorhill** [comment]
["Malicious URL Blocklist"](https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-domains.txt) contains `192.168.1.1`.

You can select "no filtering" for your router until resolved.

**Comment by JonSnow88** [comment]
Yes, Malicious URL Blocklist looks to be blocking all local resources. I've tested with it off but filtering on to confirm.

Now that's confirmed I will enable Malicious URL Blocklist but turn of filtering for local sites.

**Comment by helmar74** [comment]
Does anyone know, until when  ["Malicious URL Blocklist"](https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-domains.txt) will be fixed?

**Comment by stephenhawk8054** [comment]
> Does anyone know, until when  ["Malicious URL Blocklist"](https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-domains.txt) will be fixed?
> 

In next uBOL version

**Comment by helmar74** [comment]
> > Does anyone know, until when  ["Malicious URL Blocklist"](https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-domains.txt) will be fixed?
> 
> In next uBOL version

OK, any estimated date?
Just thinking if to wait or reconfigure all clients...

Thanks!
