### ISSUE TITLE
The counter scores increasing numbers at the tests.

### ISSUE THREAD

**Issue by SampeiNihira** [uBlockOrigin/uBOL-home#261]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality by using the _chat_ icon in the popup panel.
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBOL-home/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO Lite in the browser.

### I tried to reproduce the issue when...

- [X] uBO Lite is the only extension.
- [X] using a new, unmodified browser profile.

### Description

As specified in the title.

### A specific URL where the issue occurs.

```text
https://browserbench.org/
```

### Steps to Reproduce

1. Open this website:[https://browserbench.org/](url)
2. Run the Speedometer test 
3. The counter scores increasing numbers (this does not happen with uBlock Origin)
4. Even at the MotionMark test, the same thing happens.

### Expected behavior

By running the tests, the counter should behave as in uBlock Origin

### Actual behavior

Different from uBlock Origin.

### uBO Lite version

latest build available

### Browser name and version

Edge latest build available

### Operating system and version

W.10 Home x64

**Comment by stephenhawk8054** [comment]
I don't understand. You mean the score is higher than with uBO, so it should be "lower" to be the same as uBO?

**Comment by SampeiNihira** [comment]
> I don't understand. You mean the score is higher than with uBO, so it should be "lower" to be the same as uBO?

Try running a test with uBlock Origin Lite.
The counter score will increment as the test run time passes.
With uBlock Origin this does not happen.

**Comment by stephenhawk8054** [comment]
Hmm... The blocked number keeps increasing, although I don't see any networks being blocked in the console.

**Comment by SampeiNihira** [comment]
That's right.

**Comment by gorhill** [comment]
It's the `permissions=` filters. uBO doesn't count them. The DNR API counts them, uBOL doesn't control the badge number, it's entirely under the control of the browser.

![image](https://github.com/user-attachments/assets/67db4ca3-27e9-4de0-a97b-956be0c0ba72)

**Comment by SampeiNihira** [comment]
From the response it seems inputable to MV3.
But I did the Speedometer test with AdGuard Adblocker v.5.x and it behaves identically to uBlock Origin.

So my conclusion is that the behavior of uBlock origin Lite is not consistent with an MV3 hardship.

Merry Christmas!!

**Comment by stephenhawk8054** [comment]
Adguard MV3 does not have `permission` filters by default if I'm not wrong. Therefore there's nothing reported by the browser as expected.

**Comment by gorhill** [comment]
I don't understand what you are saying. Nobody mentioned "hardship" here before you did.

A primary feature of uBO Lite is efficiency, and that is best accomplished by letting the browser update itself the badge count according to its own DNR engine outcome. AdGuard is embedding and scanning its own internal engine data for every network request on top of the browser's own DNR engine, so they explicitly made the choice to bear the overhead burden and control the badge.

**Comment by gorhill** [comment]
> Adguard MV3 does not have permissions filters by default if I'm not wrong

_AdGuard Tracking Protection filter_ is not enabled by default, and anyways their `permissions=` filters are meant to apply only on top document, not embedded ones. Still, they do not count header injection anyways.
