### ISSUE TITLE
Scrolling issues on the settings page after zooming

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBOL-home#67]
Ungoogled Chromium (scroll is cut off after zooming):

https://github.com/uBlockOrigin/uBOL-home/assets/17685483/053f5cc8-285b-4138-b653-3bcebb62a8e6

Firefox (the glitchy auto-scroll stuff happens on its own):

https://github.com/uBlockOrigin/uBOL-home/assets/17685483/82fc8f9e-6e1a-49ef-a8c0-f8875b7f5650

**Comment by gorhill** [comment]
Why is it weird? If it was not there you wouldn't be able to see the content at the bottom.

**Comment by gorhill** [comment]
Yes, now the scrollbar is moved to the actual scrollable area, as this allows to have sticky sections in a pane, for example the upper part of "Filter lists" pane. I don't see the scrollbar in a different position being an issue, you just got used to have it elsewhere, eventually you will get used to see it where it is now.
