### ISSUE TITLE
velicu.eu: nuisance (Content scripts are not injected the first time in incognito mode)

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBOL-home#82]
`https://velicu.eu/`

uBlock Origin Lite 2023.10.21.720
Edge version 118.0.2088.76

Enabled Filterlists :
Ads, trackers, miners, and more
AdGuard – Other Annoyances
AdGuard – Social Media
AdGuard – Widgets
AdGuard/uBO – Overlays
Easylist/uBO – Cookie Notices
AdGuard URL Tracking Protection 
Block Outsider Intrusion into LAN
🇨🇳cn🇹🇼tw: AdGuard Chinese

1. Set the default filtering mode to Complete
2. Close the browser
3. Open Inprivate browsing mode and visit the website
4. The banner won't be removed unless you change the mode into Optimal and change it back into Complete.

**Comment by TotalImportance8529** [comment]
Switching uBOL mode in a new inPrivate mode tab fixed this issue on all website

**Comment by gorhill** [comment]
> The banner won't be removed

What banner? How does it look like?

**Comment by TotalImportance8529** [comment]
yes

**Comment by TotalImportance8529** [comment]
> I guess you mean the cookie-related one at the bottom?

Yes

**Comment by TotalImportance8529** [comment]
Will also happen on `https://msuic.amazon.co.uk`

**Comment by TotalImportance8529** [comment]
Never mind, just a very small bug.

**Comment by gorhill** [comment]
> Never mind, just a very small bug.

**Comment by gorhill** [comment]
I know all this (uBO uses split). The issue is the browser is not injecting the MV3-registered  content script the first time. Force a reload of the page then they are injected. uBOL is not involved in injecting these content scripts beyond registering them -- so this all points to a browser issue.
