### ISSUE TITLE
YouTube Video player will be blocked after 2 videos

### ISSUE THREAD

**Issue by OsamaAbbas** [uBlockOrigin/uBOL-home#83]
Hello,

Can uBlock Origin Lite solve this new issue?

![image](https://github.com/uBlockOrigin/uBOL-home/assets/3346502/12a97d65-1729-445a-a1cc-0bf8c34f2f56)

**Comment by Meyers07** [comment]
try adding secure DNS, such as this:
https://dns.adguard.com/dns-query 
copy and paste the link to the custom secure dns
Worked for me in at least three different systems connected under one network.
And i am not using Google Chrome (i use Microsoft Edge instead)

**Comment by Meyers07** [comment]
add an ad-blocking secure DNS on top of the extension. It may help. Linking or mentioning one might break the guideline here despite being not illegal.

**Comment by gorhill** [comment]
DNS blocking is not equipped to deal with Youtube ads or ad detection, that's just [an improper advice](https://twitter.com/gorhill/status/1712449569693315284) that is not helping OP, hence why we flag such advice.

The real answer to to follow **all** steps at <https://github.com/uBlockOrigin/uAssets/issues/20586>.

**Comment by OsamaAbbas** [comment]
I was able to block this anti-adblock using a custom script. However, it would be nice if uBlock Origin Lite could get the job done, because eventaully, it will be all we have after v2 support is dropped.

**Comment by Meyers07** [comment]
What happened to me after the anti-adblocker became public in October:
Three machines, all using Microsoft Edge, with strict tracking prevention (built in settings), do not track off, enhanced security off, using Ublock Origin Lite, and custom secure ad blocking DNS, doesn't get hit by warning.
Firefox, using only ublock origin and custom secure ad blocking DNS, all other setting default (tracking prevention standard), got hit by the warning at least three times. It doesn't appear anymore itself after removing the cache (two systems) and system reinstalling (one systems, the reinstall is for an unrelated reason)

For reference to check for possible extension conflict, there is no other extension apart from the automatically installed but inactive "Google Docs Offline" in Edge (and i immediately uninstall it) and Dark Reader (total extension in Edge: 2). Firefox also has a youtube downloader extension verified by Mozilla itself, but that isn't the issue as i keep it (total extension in Firefox: 3).

Gorhill might understand that "this broke rules" or "improper advice", but that is what worked for me and i am making sure not doing anything illegal

**Comment by stephenhawk8054** [comment]
YouTube anti-adblock is not a 1+1=2 situation. What works for you won't work for others if you don't investigate its code.

I have the same account on 1 machine in 2 browsers, with same network settings. One is getting flagged, and one is not.

**Comment by PrivacySuite** [comment]
> I was able to block this anti-adblock using a custom script. However, it would be nice if uBlock Origin Lite could get the job done, because eventaully, it will be all we have after v2 support is dropped.

I don't suppose you'd still have that script handy (assuming it still functions as intended), would you?
